### ISSUE TITLE
readme instructions show wrong library name

### ISSUE THREAD

**Issue by hptechdesign** [dangarbri/pico-distance-sensor#1]
Hi there,
Thanks for the useful library!

A minor comment - I had some trouble setting up with my CMakeLists.txt, until I checked pico-distance-sensor/src/CMakeListst.txt and realised that you called the library "distance-sensor" and not "pico-distance-sensor".

So I think the readme instructions should change as below? 

From
```
# include it in your link libraries
target_link_libraries(your_program pico_stdlib pico-distance-sensor)
```

to
```
# include it in your link libraries
target_link_libraries(your_program pico_stdlib distance-sensor)
```

**Comment by dangarbri** [comment]
Oh shoot, my bad. I'll update the readme.

Thanks!
